### ISSUE TITLE
Implement testing strategy for deduplication logic in clean stage (using dbt v1.8+ unit-tests)

### ISSUE THREAD

**Issue by MattTriano** [MattTriano/analytics_data_where_house#213]
In May 2024, `dbt` released [v1.8](https://github.com/dbt-labs/dbt-core/releases/tag/v1.8.0), which introduced a much richer [unit-testing framework](https://docs.getdbt.com/docs/build/unit-tests). I want to use this to test the logic of different transformations, starting with incremental models that deduplicate records (selecting the latest version of each record) into the `clean` stage.

## Scoping details
Data Source properties:
* returns the full dataset
* records can be updated

`data_raw` stage properties:
* all distinct versions of records are retained
* the time of ingestion is added

**Comment by MattTriano** [comment]
I've got an initial [stub of a unit-test](https://github.com/MattTriano/analytics_data_where_house/blob/9cbeded2104a41d97e0bfab2171694a944b292d4/airflow/dbt/models/clean/test_incremental_dedupe_logic.yml) running, and at present I'm executing the test via [this task in this utility DAG](https://github.com/MattTriano/analytics_data_where_house/blob/9cbeded2104a41d97e0bfab2171694a944b292d4/airflow/dags/run_dbt_cmd.py#L14).

![image](https://github.com/user-attachments/assets/25dbca3b-9994-4452-9250-ed30256d4577)

This only checks a single case (that the dedupe logic will select the latest record version), but it is easy to extend with more cases.

## Important finding
`dbt` unit-tests don't require mock data for all of the columns in the referenced datasets (or `models`). This makes it much easier to write succinct tests, and makes adding tests much less of a burden.

**Comment by MattTriano** [comment]
## Notes on writing incremental tests:

* Inputs:
    * The `input: this` input should be the records in the target table at the beginning of the current run.
    * The `ref('table_name')` input(s) consists of the records in the upstream model.
        * If there are new or updated records, they should be in this input (or another one like it).
* Expected Outputs: 
    *  The new or updated records returned by the incremental model when fed the `ref('table_name)` input(s), where the `updated_at` value is greater than the `max(updated_at)` value in the `this` table.


[Example unit_test](https://docs.getdbt.com/docs/build/unit-tests#unit-testing-incremental-models) from `dbt`'s `unit_test` docs.
```yml
unit_tests:
  - name: my_incremental_model_incremental_mode
    model: my_incremental_model
    overrides:
      macros:
        # unit test this model in "incremental" mode
        is_incremental: true 
    given:
      - input: ref('events')
        rows:
          - {event_id: 1, event_time: 2020-01-01}
          - {event_id: 2, event_time: 2020-01-02}
          - {event_id: 3, event_time: 2020-01-03}
      - input: this 
        # contents of current my_incremental_model
        rows:
          - {event_id: 1, event_time: 2020-01-01}
    expect:
      # what will be inserted/merged into my_incremental_model
      rows:
        - {event_id: 2, event_time: 2020-01-02}
        - {event_id: 3, event_time: 2020-01-03}
```

## Cases to test

- [ ] Full refresh / Basic dedupe scheme 
    - [ ] The model should select the freshest version of every record.

- [ ] Incremental Mode
    - [ ] The model should only add new or updated records from after the latest `updated_at` time observed in the target (ie output) model.
    - [ ] Excludes previously unobserved records with `updated_at` times before the latest `updated_at` time in the target model.
        - This situation (ie delayed reporting of records) can't happen when the timestamp column used to identify new|updated records accurately reflects the time the record-version was updated, but this can happen if the time-filter column reflects the a record-relevant time that won't change (e.g. `time_of_event`) and there's delayed reporting by the data source. This is an undesirable situation but it can be handled by periodically running a full refresh.
