### ISSUE TITLE
Configure the DWH database for more analytical workloads

### ISSUE THREAD

**Issue by MattTriano** [MattTriano/analytics_data_where_house#242]
Postgres's default config is more optimized for transactional workloads (many concurrent queries/commands returning/updating single records) but I'm using that database mainly for analytical workloads (fewer queries/ingestions moving potentially large amounts of data). While it hasn't been too big of an issue yet, I've started brushing up against situations where I'd like better performance.

* `shared_buffers`
    * Allocates memory for caching data (to avoid expensive I/O ops)
    * Preallocates memory exclusively to postgres (i.e., this memory is tied up).
    * Guidance: up to 25% to 40% of system RAM
* `work_mem`
    * Max memory available for a single query operation (e.g., sorting, merging, hashing, etc)
    * Does not preallocate memory.
    * Guidance: up to 2% of RAM (although ~64MB is typically adequate; the default is 4MB)
* `max_connections`
    * The max number of concurrent connections. Default is 100
*  `maintenance_work_mem`
    * Max memory available for maint ops (e.g. `VACUUM`, `CREATE INDEX`, etc)
    * Not preallocated.
    * Guidance: up to 5% of system RAM (default is 64MB)
* `effective_cache_size`
    * Guidance for the query optimizer, does not actually govern system memory usage
    * Guidance: up to 70% of RAM
* `max_wal_size`
    * The WAL (Write Ahead Log) prevents data loss in case of system failure by staging transactions in a log before committing them in the database. If the system fails, postgres compares the log against the data in the database and reconciles the diff from the last checkpoint. This is vital when handling many small transactions from many different users but it's just extra overhead when running idempotent ingestion or transformation jobs.
    * Guidance: about as large as the bigest datasets being ingested (default is 1GB)
* `checkpoint_timeout`
    * Max time between automatic WAL checkpoints (assuming the WAL has changed)
    * Guidance: increase it (default: 5 minutes)
   
Also a good idea to increase the number of CPUs available for processes (e.g. via `max_worker_processes`)

I'm running my system on a local machine that I built that has plenty of RAM, but I don't want to assume users have comparable systems. I should check what env-vars are already expected per the source PostGIS docker image and possible add some env-vars to my Dockerfile to enable setting these configs via env-vars.

![image](https://github.com/user-attachments/assets/3ea11727-8eb5-434e-9c59-1f8e9f1b41c0)

**Comment by MattTriano** [comment]
Pulling config values into env-vars is a bit trickier than I had hoped. As I've tracked the `postgresql.conf` file (to include [this line](https://github.com/MattTriano/analytics_data_where_house/blob/a3bd7438c4316f827874843d57d5b5333a4a0249/docker/postgis/postgresql.conf#L740) which enables an extension needed by OpenMetadata services), I can't use a solution that edits values into the `postgresql.conf` file. I also researched to see if postgres supports bash-style variable substitution in `postgresql.conf` files and everything I read indicates it's not supported.

It is possible to pass in configs when starting up a postgres server via the `-c` option and I committed a [failed experiment](https://github.com/MattTriano/analytics_data_where_house/blob/d235f0fa70807e628f203e1df3e6b0bb93326cb0/docker-compose.yml#L278) exploring this concept, and I want to document why it failed and think through a potential way to make it work.

In that experiment, I added env-vars to my `.env.dwh` file and added this command to the `dwh_db` service in `docker-compose.yml`.

```yml
  dwh_db:
    ...
    env_file:
      - .env.dwh
    command: >
      postgres -c work_mem=${POSTGRES_WORK_MEM:-64MB}
               -c maintenance_work_mem=${POSTGRES_MAINTENANCE_WORK_MEM:-512MB}
               -c max_connections=${POSTGRES_MAX_CONNECTIONS:-50}
               -c effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE:-8GB}
               -c checkpoint_timeout=${POSTGRES_CHECKPOINT_TIMEOUT:-15min}
               -c max_wal_size=${POSTGRES_MAX_WAL_SIZE:-4GB}
               -c shared_buffers=${POSTGRES_SHARED_BUFFERS:-8GB}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "dwh_db",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}"
        ]
      interval: 5s
      retries: 5
```

I expected `docker compose` would substitute env-vars from the named `env_file` into the command, but when I restarted my system and checked the values of configs where I set values other than the default, I found that the defaults were being used.

![image](https://github.com/user-attachments/assets/dbd8cb53-bb85-498b-a807-126042ed67db)

and `docker compose config` showed

```yml
  dwh_db:
    ...
    command:
      - postgres
      - -c
      - work_mem=64MB
      - -c
      - maintenance_work_mem=512MB
      - -c
      - max_connections=50
      - -c
      - effective_cache_size=8GB
      - -c
      - checkpoint_timeout=15min
      - -c
      - max_wal_size=4GB
      - -c
      - shared_buffers=8GB
    environment:
      POSTGRES_CHECKPOINT_TIMEOUT: 15min
      POSTGRES_DB: re_dwh
      POSTGRES_EFFECTIVE_CACHE_SIZE: 24GB
      POSTGRES_MAINTENANCE_WORK_MEM: 2GB
      POSTGRES_MAX_CONNECTIONS: "10"
      POSTGRES_MAX_WAL_SIZE: 4GB
      POSTGRES_PASSWORD: admin_db_password
      POSTGRES_SHARED_BUFFERS: 24GB
      POSTGRES_USER: admin_db_username
      POSTGRES_WORK_MEM: 128MB
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -h
        - dwh_db
        - -d
        - re_dwh
        - -U
        - admin_db_username
```

Env-vars were correctly parsed into the `healthcheck` section, but they weren't being parsed correctly into the `command` section. I erroneously expected env-vars would from the named `env_file` would be parsed into their invocations within the service, and in investigating why this didn't work, I've learned more about how `docker compose` handles env-vars and [env-var precedence](https://docs.docker.com/compose/how-tos/environment-variables/envvars-precedence/) in `docker compose`.

When `docker compose` evaluates a `docker-compose.yml` file, it loads env-vars from the file named `.env` (or the file specified by the `--env-file` option **passed in via the CLI**) into a global namespace and interpolates those values into matching variables in the `docker-compose.yml` file. Env-vars set via the `env_file:` `docker compose` field have a lower precedence and (if my understanding of the docker compose documentation is correct) should be ignored in favor of the `.env` file's env vars.

HOWEVER, when I compare the `docker compose config` output for the [airflow_db healthcheck](
https://github.com/MattTriano/analytics_data_where_house/blob/d235f0fa70807e628f203e1df3e6b0bb93326cb0/docker-compose.yml#L235) against the [dwh_db healthcheck](https://github.com/MattTriano/analytics_data_where_house/blob/d235f0fa70807e628f203e1df3e6b0bb93326cb0/docker-compose.yml#L264), I found that both used the `.env.dwh` values. So there's something that needs to be debugged here.

```yml
healthcheck:
      test:
        - CMD
        - pg_isready
        - -d
        - re_dwh (POSTGRES_DB from .env.dwh)
        - -U
        - POSTGRES_USER from .env.dwh
```

- [ ] Debug this issue
- [ ] Explore alternate options for handling configs.
